[package]
name = "georender-pack"
version = "0.1.0"
authors = ["okdistribute <633012+okdistribute@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbf = "0.1"
kv = "0.20.2"
serde_json = "1.0"
serde = "1.0.105"
