[package]
name = "georender"
version = "0.1.0"
authors = ["okdistribute <633012+okdistribute@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbf = "0.1"
kv = "0.20.2"
desert = "1.0.3"
varinteger = "1.0.6"
regex = "1"
lazy_static = "1.4.0"
failure = "0.1.8"

[[example]]
name = "pack"
path = "example/pack/main.rs"
required-features = [ ]
